### ISSUE TITLE
Cheerlights color no longer updating

### ISSUE THREAD

**Issue by spiff72** [kd8bxp/Cheerlights_Clock#4] opened 2020-06-30 16:58 UTC
Hello - I'm back again!  Just noticed that my cheerlights clock seems to be stuck in "magenta" color - and has been for quite some time.  I am not sure if this is an issue with the mqtt server or a cheerlights problem, but I changed the color with a cheerlight tweet earlier today and it appeared that their Thingspeak channel updated correctly, but it didn't update on the clock.

Not a big deal, but I just wanted to ask.  I have been running my customized version of the code but I tried flashing your original code back to the device and it doesn't update either.

Thanks!

**Comment by spiff72** [comment] 2020-06-30 17:07
Here is the serial output I get after booting:

```
Attempting MQTT connection...12:00 AM
Time Updated
13:03:04
connected
Message arrived in topic: cheerlights
Message:magenta
-----------------------
magenta
Message arrived in topic: cheerlights/rgb565Decimal
Message:63519
-----------------------
*******
63519
01:03 PM
01:03 PM

```
The color should be yellow right now based on this page:
https://thingspeak.com/channels/1417

**Comment by kd8bxp** [comment] 2020-06-30 17:13
I suspect it's a MQTT server issue - which is a probably when "we" are using a 3rd party server it's kind of out of our control if it goes down.

I'm in the middle of a big project right now - but I'll look into it sometime tonight or tomorrow.  Hopefully by then the MQTT broker will be working again, and the issue will resolve itself.

**Comment by spiff72** [comment] 2020-06-30 17:14
no problem - and absolutely no rush.  was just something that I noticed today so posted an issue.

**Comment by kd8bxp** [comment] 2020-07-02 21:03
I can confirm it is no longer working :-( Might take me a few days, still working on the larger project, but I think we can change to the official mqtt.cheerlights.com mqtt broker without a whole lot of changes - there are of course going to be some because it works a bit different - but I don't think it will be hard to fix - just might take a few days to do it.

**Comment by kd8bxp** [comment] 2020-07-02 21:13
P.S. I did leave a message on twitter to the people that originally started this project - I think one of them runs the current mqtt broker - and maybe they will beable to reset it or something - But it's probably a good idea to make the move to the official broker anyways. So I will work on that soon(ish)

**Comment by spiff72** [comment] 2020-07-03 01:10
Sounds good - thanks!

**Comment by kd8bxp** [comment] 2020-07-03 01:58
Great news  - Simon Walters cymplecy on twitter does run the mqtt broker - he was busy on another project as well, but said he'd try to look at it tomorrow, so it might just start working again.  
I'll work on making the changes as well and let you know.

**Comment by spiff72** [comment] 2020-07-03 02:45
Awesome - thanks!

**Comment by spiff72** [comment] 2020-07-03 17:31
I think it may have been fixed now.  I just noticed my clock is red, and this matches the thingspeak channel color i linked to above!

**Comment by kd8bxp** [comment] 2020-07-03 20:13
Yes Simon is working on his broker now, He told me that he moved the broker from a raspberry pi zero to a Win 10 machine - that will give him some time to work on the pi zero and see what is going on with it - He also changed things to get his feed from the official MQTT broker - so with that being said I think I'm closing this issue.
Over the next few days you may (or may not) notice some little hiccups - He did say that switching his feed to the mQTT made everything a little slower (understandable, the official broker is not the fastest thing either).
I'm trying to think of a way to have both brokers in the sketch one for backup of the other - not sure yet if that is something that can be done - got to put the thinking cap on.
But with the current broker being worked on, and all I'm going to close this - and we will go from there.

**Closed as completed by kd8bxp** 2020-07-03 20:13 UTC

**Comment by spiff72** [comment] 2020-07-03 20:31
Sounds good - i was getting tired of looking at the same color all the time. :-)
